name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install Playwright
      run: npm install @playwright/test

    - name: Install Playwright Dependencies
      run: npx playwright install-deps
      
    - name: Install dependencies
      run: dotnet restore AllureMain.sln
      
    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Install Playwright Browsers
      run: pwsh AllureMain.Tests/bin/Debug/net8.0/playwright.ps1 install

    - name: Build the project
      run: dotnet build AllureMain.sln --no-restore
      
    - name: Run Playwright tests
      run: dotnet test AllureMain.Tests/AllureMain.Tests.csproj --configuration Release --verbosity normal 
          
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    # Publish Allure Report
    - name: Build and Publish Allure Report
      uses: simple-elf/allure-report-action@v1.1
      if: always()
      with:
        allure_results: ./allure-results  # Path where Allure results are stored
        gh_pages: gh-pages
        allure_history: allure-history

    # Publish test report to GitHub Pages
    - name: Publish Allure Test Report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
